### ISSUE TITLE
File handle of the .eso can be left open when an exception is hit

### ISSUE THREAD

**Issue by jamiebull1** [architecture-building-systems/esoreader#1]
This one just cropped up while I was using esoreader to handle my results. I was trying to do this (I'm sure there's a better way but it seems to work in most cases):
```python
outputs['gas'] = eso.to_frame('Gas:Facility', frequency='RunPeriod')[None][0]
```
The problem is if there's no `Gas:Facility` in the .eso then this throws an exception. That then leaves the file handle open which means when I try to delete the temp directory I get an `OSError`.

The simple solution is to use a context handler when opening the file.

```python
def read_from_path(eso_file_path):
    """
    read in a .eso file and return an EsoFile object that can be used
    to read in pandas DataFrame and Series objects.
    """
    with open(eso_file_path, 'r') as eso_file:
        eso = EsoFile(eso_file)
    return eso
```

**Comment by daren-thomas** [comment]
good catch! i'll fix it as soon as i get time - probably september 14.

**Comment by daren-thomas** [comment]
fixed in trunk. next actions:
- update they version on pypi
- install from pypi and test that it still works
